name: plus1-mvp
services:
  - name: web
    git:
      branch: main
      repo_clone_url: ${_REPO_URL}
    build_command: next build --no-lint
    run_command: npm start
    envs:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: ${_SUPABASE_URL}
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: ${_SUPABASE_ANON_KEY}
      - key: NEXT_PUBLIC_SITE_URL
        value: ${_SITE_URL}
      - key: NEXT_PUBLIC_APP_URL
        value: ${_APP_URL}
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    routes:
      - path: /
    build_cache:
      enabled: true
      paths:
        - node_modules
        - .next/cache 