name: plus1-mvp
region: nyc
services:
  - name: web
    git:
      branch: main
      repo_clone_url: https://github.com/plus1-club/plus1-mvp-base.git
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    build_command: |
      npm run build
      # Create clean deployment directory
      mkdir -p /workspace/deploy
      # Copy files exactly as in Docker
      cp -r .next/standalone/* /workspace/deploy/
      cp -r .next/static /workspace/deploy/.next/
      cp -r public /workspace/deploy/
      cp next.config.js /workspace/deploy/
      cp package.json /workspace/deploy/
      # Move to deployment directory
      cd /workspace/deploy
    run_command: NODE_ENV=production node server.js
    source_dir: /workspace/deploy
    envs:
      - key: NEXT_PUBLIC_SUPABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: ${NEXT_PUBLIC_SUPABASE_URL}
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - key: NODE_ENV
        scope: RUN_AND_BUILD_TIME
        value: production
      - key: PORT
        scope: RUN_AND_BUILD_TIME
        value: "3000"
      - key: HOSTNAME
        scope: RUN_AND_BUILD_TIME
        value: "0.0.0.0"
    build_cache:
      paths:
        - .next/cache
        - node_modules
    health_check:
      http_path: /
      initial_delay_seconds: 30
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    routes:
      - path: /_next/static
        serve_static: true
        dir: .next/static
      - path: /public
        serve_static: true
        dir: public
ingress:
  rules:
    - component:
        name: web
      match:
        path:
          prefix: /
      preserve_path_prefix: true
    - component:
        name: web
      match:
        path:
          prefix: /_next
      preserve_path_prefix: true
features:
  - buildpack-stack=ubuntu-22
static_sites:
  - name: next-static
    environment_slug: html
    github:
      branch: main
      deploy_on_push: true
      repo: plus1-club/plus1-mvp-base
    routes:
      - path: /_next/static
        serve_static: true
        dir: .next/static
      - path: /public
        serve_static: true
        dir: public
envs:
  - key: NODE_ENV
    scope: RUN_AND_BUILD_TIME
    value: production
  - key: NEXT_PUBLIC_SUPABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: ${NEXT_PUBLIC_SUPABASE_URL}
  - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: ${NEXT_PUBLIC_SUPABASE_ANON_KEY} 