name: plus1-mvp
region: nyc
services:
  - name: web
    git:
      branch: main
      repo_clone_url: https://github.com/plus1-club/plus1-mvp-base.git
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    build_command: |
      npm run build
      mkdir -p standalone/.next
      cp -r .next/standalone/* standalone/
      cp -r .next/static standalone/.next/static
      cp -r public standalone/public
    run_command: cd standalone && NODE_ENV=production node server.js
    source_dir: /
    envs:
      - key: NEXT_PUBLIC_SUPABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: ${NEXT_PUBLIC_SUPABASE_URL}
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - key: NODE_ENV
        scope: RUN_AND_BUILD_TIME
        value: production
      - key: PORT
        scope: RUN_AND_BUILD_TIME
        value: "3000"
      - key: HOSTNAME
        scope: RUN_AND_BUILD_TIME
        value: "0.0.0.0"
    build_cache:
      paths:
        - node_modules
ingress:
  rules:
    - component:
        name: web
      match:
        path:
          prefix: /plus1-mvp-dep2
      preserve_path_prefix: true
    - component:
        name: web
      match:
        path:
          prefix: /plus1-mvp-dep2/_next
      preserve_path_prefix: true
    - component:
        name: web
      match:
        path:
          prefix: /plus1-mvp-dep2/static
      preserve_path_prefix: true
    - component:
        name: web
      match:
        path:
          prefix: /plus1-mvp-dep2/public
      preserve_path_prefix: true
features:
  - buildpack-stack=ubuntu-22
envs:
  - key: NODE_ENV
    scope: RUN_AND_BUILD_TIME
    value: production
  - key: NEXT_PUBLIC_SUPABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: ${NEXT_PUBLIC_SUPABASE_URL}
  - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: ${NEXT_PUBLIC_SUPABASE_ANON_KEY} 